## Introduction to Data Science (Project - Phase 0)
### Mohamad Mahdi Samadi (810101465)
### Kasra Ghorbani Aghil Abadi (810101489)

Dataset Name: Football players salaries

Dataset Link: [Link](https://www.kaggle.com/datasets/ultimus/football-salaries-dataset)

Target Variable: Salary

In [28]:
import pandas as pd
df = pd.read_csv("./raw_wages.csv")
print(f"Sample size is {len(df)}")
df.head(n=5)

Sample size is 40791

,Name,Club,Division,Based,Nat,EU National,Caps,AT Apps,Position,Age,CR,Begins,Expires,Last Club,Last Trans. Fee,Salary
0,Cristiano Ronaldo - Portuguese,Al-Nassr (KSA) - Roshn Saudi League,Roshn Saudi League ...,Saudi Arabia (Saudi Pro League) ...,POR,Yes,200.0,673,ST (C),38.0,"7,629",31/12/2022,30/6/2025,,-,"€203,478,000 p/a"
1,Karim Benzema - French,Al-Ittihad - Roshn Saudi League,Roshn Saudi League ...,Saudi Arabia (Saudi Pro League) ...,FRA,Yes,97.0,555,ST (C),35.0,"8,250",1/7/2023,30/6/2025,,-,"€199,452,000 p/a"
2,Neymar - Brazilian,Al-Hilal (KSA) - Roshn Saudi League,Roshn Saudi League ...,Saudi Arabia (Saudi Pro League) ...,BRA,Yes,124.0,340,"AM (LC), ST (C)",31.0,"9,000",15/8/2023,30/6/2025,Paris Saint-Germain,€90M,"€149,589,000 p/a"
3,Ezri Konsa - English,Al-Hilal (KSA) - Roshn Saudi League,Roshn Saudi League ...,Saudi Arabia (Saudi Pro League) ...,ENG,No,0.0,245,D (C),25.0,"7,414",27/8/2023,30/6/2027,Aston Villa,€55M,"€74,157,000 p/a"
4,Kylian Mbappé - French,Paris Saint-Germain - Ligue 1 Uber Eats,Ligue 1 Uber Eats ...,France (Ligue 1) ...,FRA,Yes,70.0,221,"AM (RL), ST (C)",24.0,"9,415",22/7/2023,30/6/2028,Monaco,€186M,"€48,467,000 p/a"